### ISSUE TITLE
Remove sticker command doesn't work

### ISSUE THREAD

**Issue by AnyByte** [Unthrottled/doki-theme-vscode#14]
**Describe the bug**
Selecting "Remove Sticker/Background" option replaces sticker to Hatsune Miku and doesn't actually remove it.

**To Reproduce**
1. Install one of stickers
2. Try to remove the sticker with "Remove Sticker/Background" option

**Actual Behaviour**
Sticker is not removing

**Expected Behavior**
Removed sticker and uncorrupted VSCode css

**Comment by AnyByte** [comment]
> 
> 
> Hey! So did you reload/restart your vscode? That step is necessary.

Yes, multiple times and sticker still persisted.

**Comment by Unthrottled** [comment]
Oh wow, I must have goofed something up on my end....

If you want to fix it before I get an update out, you can do this:

Here is where vs code stores the CSS
```
(base) λ pringle ~ → ll /usr/share/code/resources/app/out/vs/workbench
total 8476
drwxr-xr-x 5 alex root    4096 Jun 11 19:09 .
drwxr-xr-x 7 root root    4096 May 15 04:35 ..
drwxr-xr-x 3 alex root    4096 Feb 16 07:25 browser
drwxr-xr-x 8 alex root    4096 May 15 04:35 contrib
-rw-r--r-- 1 alex alex  308509 Feb 16 08:05 css.copy
drwxr-xr-x 4 alex root    4096 Feb 16 07:25 services
-rw-r--r-- 1 alex alex  353689 Jun 11 19:09 workbench.desktop.main.css
-rw-r--r-- 1 alex alex  352872 Jun 11 19:09 workbench.desktop.main.css.copy
-rw-r--r-- 1 alex root 7319411 May 14 03:13 workbench.desktop.main.js
-rw-r--r-- 1 alex root  312190 May 14 03:13 workbench.desktop.main.nls.js
```

I made a copy of the original CSS, however, some how I wrote to the CSS copy. :disappointed: 

You can try to restore your CSS file by replacing the original with the copy and cutting off the sticker stuff, which is at the bottom of the file. (it's a big file)

**Comment by Unthrottled** [comment]
@AnyByte 

There is a new version of the extension (2.4.2) that fixes this issue.

Once you updated to 2.4.2, please note that when _you_ run the `Remove Sticker/Background` you will not get a message telling you to reload your VSCode (As you already removed before). After you you run the remove command just reload the editor and you should be back to normal.

Thank you for you patience. Let me know if you have any more issues.
